// Generated by scripts/generate-controllers.mjs — 禁止手改。
// 绑定层:把 orval 按 tag 生成的工厂函数实例化为单例,页面统一 XxxController.xxx() 调用。

import { getAuth } from "./generated/auth/auth";
import { getConfigs } from "./generated/configs/configs";
import { getDicts } from "./generated/dicts/dicts";
import { getLogs } from "./generated/logs/logs";
import { getMedia } from "./generated/media/media";
import { getPermissions } from "./generated/permissions/permissions";
import { getRoles } from "./generated/roles/roles";
import { getSystem } from "./generated/system/system";
import { getUploads } from "./generated/uploads/uploads";
import { getUsers } from "./generated/users/users";

export const AuthController = getAuth();
export const ConfigsController = getConfigs();
export const DictsController = getDicts();
export const LogsController = getLogs();
export const MediaController = getMedia();
export const PermissionsController = getPermissions();
export const RolesController = getRoles();
export const SystemController = getSystem();
export const UploadsController = getUploads();
export const UsersController = getUsers();
