// Generated by scripts/generate-controllers.mjs — 禁止手改。
// 绑定层:把 orval 按 tag 生成的工厂函数实例化为单例,页面统一 XxxController.xxx() 调用。

import { getH5 } from "./generated/h5/h5";

export const H5Controller = getH5();
