// 既有 5 条源码断言用例(node --test 时代的 smoke 测试)整体迁移到 vitest,
// 断言价值原样保留:防 basename 类结构性回归(纯文件断言,无需 DOM,用 node 环境)。
// @vitest-environment node
import { readFile } from "node:fs/promises";

import { expect, test } from "vitest";

const packageJson = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
const pageSource = await readFile(new URL("../src/routes/page.tsx", import.meta.url), "utf8");
const layoutSource = await readFile(new URL("../src/routes/layout.tsx", import.meta.url), "utf8");
const configSource = await readFile(new URL("../modern.config.ts", import.meta.url), "utf8");

test("admin app exposes standard lifecycle scripts", () => {
  expect(packageJson.scripts.dev).toBe("modern dev");
  expect(packageJson.scripts.build).toBe("modern build");
  expect(packageJson.scripts["build:github-pages"]).toBe("modern build");
  expect(packageJson.scripts["deploy:github-pages"]).toBe("pnpm --workspace-root run build:pages");
  expect(packageJson.scripts.typecheck).toBe("tsc --noEmit");
});

test("admin app has dashboard home page content and Modern.js app tools configured", () => {
  // 阶段 12:欢迎页已替换为仪表盘(统计卡 + 图表,mock 纪律见 routes/dashboard/mock.ts)
  expect(pageSource).toMatch(/PageContainer/);
  expect(pageSource).toMatch(/useDashboardData/);
  expect(layoutSource).toMatch(/Outlet/);
  expect(configSource).toMatch(/appTools\(\)/);
});

test("admin uses static permission-filtered menus and generated controller layer", async () => {
  const notFoundSource = await readFile(
    new URL("../src/components/not-found.tsx", import.meta.url),
    "utf8"
  );
  expect(notFoundSource).toMatch(/Result/);
  expect(notFoundSource).toMatch(/status="404"/);

  const menuSource = await readFile(new URL("../src/config/menu.tsx", import.meta.url), "utf8");
  expect(menuSource).toMatch(/filterMenusByPermissions/);
  expect(menuSource).toMatch(/"menu:system:user"/);
  expect(menuSource).toMatch(/hasMenuPermission/);
  expect(menuSource).not.toMatch(/componentKey/i);

  const authGateSource = await readFile(
    new URL("../src/components/auth-gate.tsx", import.meta.url),
    "utf8"
  );
  expect(authGateSource).toMatch(/Tooltip/);
  expect(authGateSource).toMatch(/usePermission/);

  const controllersGen = await readFile(
    new URL("../src/api/controllers.gen.ts", import.meta.url),
    "utf8"
  );
  expect(controllersGen).toMatch(/Generated by scripts\/generate-controllers\.mjs/);
});

test("admin app config supports repository-scoped GitHub Pages paths", () => {
  expect(configSource).toMatch(/GITHUB_PAGES_BASE_PATH/);
  expect(configSource).toMatch(/GITHUB_REPOSITORY/);
  expect(configSource).toMatch(/assetPrefix/);
  expect(configSource).toMatch(/ADMIN_ASSET_PREFIX/);
  expect(configSource).toMatch(/server: { port: devServerPort }/);
  expect(configSource).toMatch(/outputStructure: "flat"/);
  expect(configSource).toMatch(/html: ""/);
});

test("stage 0 wires openapi contract pipeline and dev proxy to the go server", async () => {
  expect(packageJson.scripts["gen:api"]).toBe(
    "orval --config ./orval.config.ts && node ./scripts/generate-controllers.mjs"
  );
  expect(
    packageJson.dependencies["@tanstack/react-query"],
    "tanstack react-query required"
  ).toBeTruthy();
  expect(packageJson.dependencies.axios, "axios required").toBeTruthy();
  expect(packageJson.dependencies.ahooks, "ahooks required").toBeTruthy();
  expect(packageJson.dependencies.lodash, "lodash required").toBeTruthy();

  const clientSource = await readFile(new URL("../src/api/client.ts", import.meta.url), "utf8");
  // 契约路径字面带 /api/admin 前缀(阶段 8),客户端不再设 baseURL:无 BASE_URL 常量、Axios.create() 不带配置。
  expect(clientSource).not.toMatch(/BASE_URL/);
  expect(clientSource).toMatch(/Axios\.create\(\)/);
  expect(clientSource).toMatch(/Authorization/);
  expect(clientSource).toMatch(/export function customInstance/);

  expect(packageJson.dependencies.zustand, "zustand required").toBeTruthy();

  const controllersSource = await readFile(
    new URL("../src/api/controllers.gen.ts", import.meta.url),
    "utf8"
  );
  expect(controllersSource).toMatch(/export const AuthController = getAuth\(\)/);
  expect(controllersSource).toMatch(/export const SystemController = getSystem\(\)/);

  const authStoreSource = await readFile(new URL("../src/store/auth.ts", import.meta.url), "utf8");
  expect(authStoreSource).toMatch(/export const useAuthStore/);

  const layoutSource2 = await readFile(
    new URL("../src/routes/layout.tsx", import.meta.url),
    "utf8"
  );
  expect(layoutSource2).toMatch(/QueryClientProvider/);
  expect(layoutSource2).toMatch(/APP_BASENAME/);

  const runtimeConfigSource = await readFile(
    new URL("../src/modern.runtime.ts", import.meta.url),
    "utf8"
  );
  expect(runtimeConfigSource).toMatch(/defineRuntimeConfig/);
  expect(runtimeConfigSource).toMatch(/basename: APP_BASENAME/);

  const configSource2 = await readFile(new URL("../modern.config.ts", import.meta.url), "utf8");
  expect(configSource2).toMatch(/proxy: \{/);
  expect(configSource2).toMatch(/API_PROXY_TARGET/);
  // 阶段 8:dev 代理原样透传,不再 pathRewrite。
  expect(configSource2).not.toMatch(/pathRewrite/);

  const generatedHealthz = await readFile(
    new URL("../src/api/generated/system/system.ts", import.meta.url),
    "utf8"
  );
  expect(generatedHealthz).toMatch(/export const getSystem/);
  expect(generatedHealthz).toMatch(/customInstance<HealthzResponse>/);
  expect(generatedHealthz).toMatch(/\/api\/admin\/healthz/);

  // 媒体内容端点为契约前缀路径(useFileURL 直取,见阶段 8)。
  const fileUrlHook = await readFile(
    new URL("../src/hooks/use-file-url.ts", import.meta.url),
    "utf8"
  );
  expect(fileUrlHook).toMatch(/\/api\/admin\/files\//);
});
